### ISSUE TITLE
How to install with Nvidia Geforce RTX 4060 TI 16GB VRAM support? By default it installs only CPU.

### ISSUE THREAD

**Issue by CRCODE22** [Eddycrack864/UVR5-UI#13]
2024-11-09 23:17:27.705 - INFO - cli - Separator version 0.24.1 beginning with input file(s): ./inputs/19495.wav
2024-11-09 23:17:27.708 - INFO - separator - Separator version 0.24.1 instantiating with output_dir: ./outputs, output_format: mp3
2024-11-09 23:17:27.709 - INFO - separator - Operating System: Windows 10.0.22631
2024-11-09 23:17:27.709 - INFO - separator - System: Windows Node: DESKTOP-47384SD Release: 10 Machine: AMD64 Proc: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
2024-11-09 23:17:27.709 - INFO - separator - Python Version: 3.10.12
2024-11-09 23:17:27.710 - INFO - separator - PyTorch Version: 2.5.1+cpu
2024-11-09 23:17:27.730 - INFO - separator - FFmpeg installed: ffmpeg version 2023-03-20-git-57afccc0ef-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
2024-11-09 23:17:27.734 - INFO - separator - ONNX Runtime GPU package installed with version: 1.20.0
2024-11-09 23:17:27.734 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
2024-11-09 23:17:27.734 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt...
2024-11-09 23:17:35.715 - INFO - mdxc_separator - MDXC Separator initialisation complete
2024-11-09 23:17:35.716 - INFO - separator - Load model duration: 00:00:07
2024-11-09 23:17:35.718 - INFO - separator - Starting separation process for audio_file_path: ./inputs/19495.wav
 11%|████████████████▉                                                                                                                                           | 5/46 [02:39<21:42, 31.77s/it]
 
 When the pinokio version still worked it ran very fast with my GPU this manual github install does not have nvidia support!

**Comment by Eddycrack864** [comment]
Oh, it seems my install script has to be modified to install torch manually, even though I'm installing the GPU version it's not working with GPU.

Just to make sure can you run this script? Using the torch of your env of course
```
import torch
print(torch.__version__)
print(f"CUDA disponible: {torch.cuda.is_available()}")
print(f"Dispositivo actual: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")
```

Also make sure you know your CUDA version using `nvidia-smi`. Supported CUDA versions are 11.8 and 12.2.

Most likely, pytorch for CPU is installed by default because `2024-11-09 23:17:27.710 - INFO - separator - PyTorch Version: 2.5.1+cpu`. So proceed like this:

First uninstall the current dependencies running
```
pip uninstall torch torchvision torchaudio
```

Then reinstall them by telling pip where to install the packages, sample for (CUDA 12.2):
```
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu122
```

Don't forget to do all this inside the env and not globally. This should fix the issue.

**Comment by CRCODE22** [comment]
Thank you for the reply here is the reply I got:

(base) K:\UVR5-UI>python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.5.1+cu121
>>> print(f"CUDA disponible: {torch.cuda.is_available()}")
CUDA disponible: True
>>> print(f"Dispositivo actual: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")
Dispositivo actual: NVIDIA GeForce RTX 4060 Ti
>>>

**Comment by CRCODE22** [comment]
(base) K:\UVR5-UI>nvidia-smi
Sun Nov 10 03:16:27 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti   WDDM  |   00000000:09:00.0  On |                  N/A |
|  0%   58C    P3             33W /  165W |    3503MiB /  16380MiB |     37%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by CRCODE22** [comment]
The last command you provided does not work:

(base) K:\UVR5-UI>pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu122
Looking in indexes: https://download.pytorch.org/whl/cu122, https://pypi.ngc.nvidia.com
Requirement already satisfied: torch in e:\anaconda3\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in e:\anaconda3\lib\site-packages (0.20.1+cu121)
ERROR: Could not find a version that satisfies the requirement torchaudio (from versions: none)
ERROR: No matching distribution found for torchaudio

**Comment by CRCODE22** [comment]
Cuda 12.2 should be Cuda 12.1?

**Comment by CRCODE22** [comment]
I have installed  torch-2.5.0+cu121 torchvision-0.20.0+cu121

Successfully installed torch-2.5.0+cu121 torchvision-0.20.0+cu121

(base) K:\UVR5-UI>pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121
Looking in indexes: https://download.pytorch.org/whl/test/cu121, https://pypi.ngc.nvidia.com
Requirement already satisfied: torch==2.5.0 in e:\anaconda3\lib\site-packages (2.5.0+cu121)
Requirement already satisfied: torchvision in e:\anaconda3\lib\site-packages (0.20.0+cu121)
Requirement already satisfied: filelock in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.12.2)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (4.12.2)
Requirement already satisfied: networkx in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2.8.4)
Requirement already satisfied: jinja2 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.1.2)
Requirement already satisfied: fsspec in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2023.6.0)
Requirement already satisfied: sympy==1.13.1 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\anaconda3\lib\site-packages (from sympy==1.13.1->torch==2.5.0) (1.2.1)
Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from torchvision) (1.23.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\anaconda3\lib\site-packages (from torchvision) (10.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda3\lib\site-packages (from jinja2->torch==2.5.0) (2.1.1)

Still the software says the following:

2024-11-10 04:06:50.474 - INFO - separator - Python Version: 3.10.12
2024-11-10 04:06:50.474 - INFO - separator - PyTorch Version: 2.5.1+cpu
2024-11-10 04:06:50.495 - INFO - separator - FFmpeg installed: ffmpeg version 2023-03-20-git-57afccc0ef-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
2024-11-10 04:06:50.499 - INFO - separator - ONNX Runtime GPU package installed with version: 1.20.0
2024-11-10 04:06:50.500 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
2024-11-10 04:06:50.500 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt...
2024-11-10 04:06:59.286 - INFO - mdxc_separator - MDXC Separator initialisation complete
2024-11-10 04:06:59.287 - INFO - separator - Load model duration: 00:00:08
2024-11-10 04:06:59.287 - INFO - separator - Starting separation process for audio_file_path: ./inputs/29951.wav

How can it still use PyTorch Version: 2.5.1+cpu when I removed it completely with "pip uninstall torch torchvision torchaudio" and installed "pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121" ?

**Comment by Eddycrack864** [comment]
> I have installed torch-2.5.0+cu121 torchvision-0.20.0+cu121
> 
> Successfully installed torch-2.5.0+cu121 torchvision-0.20.0+cu121
> 
> (base) K:\UVR5-UI>pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121 Looking in indexes: https://download.pytorch.org/whl/test/cu121, https://pypi.ngc.nvidia.com Requirement already satisfied: torch==2.5.0 in e:\anaconda3\lib\site-packages (2.5.0+cu121) Requirement already satisfied: torchvision in e:\anaconda3\lib\site-packages (0.20.0+cu121) Requirement already satisfied: filelock in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.12.2) Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (4.12.2) Requirement already satisfied: networkx in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2.8.4) Requirement already satisfied: jinja2 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.1.2) Requirement already satisfied: fsspec in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2023.6.0) Requirement already satisfied: sympy==1.13.1 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (1.13.1) Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\anaconda3\lib\site-packages (from sympy==1.13.1->torch==2.5.0) (1.2.1) Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from torchvision) (1.23.5) Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\anaconda3\lib\site-packages (from torchvision) (10.1.0) Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda3\lib\site-packages (from jinja2->torch==2.5.0) (2.1.1)
> 
> Still the software says the following:
> 
> 2024-11-10 04:06:50.474 - INFO - separator - Python Version: 3.10.12 2024-11-10 04:06:50.474 - INFO - separator - PyTorch Version: 2.5.1+cpu 2024-11-10 04:06:50.495 - INFO - separator - FFmpeg installed: ffmpeg version 2023-03-20-git-57afccc0ef-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers 2024-11-10 04:06:50.499 - INFO - separator - ONNX Runtime GPU package installed with version: 1.20.0 2024-11-10 04:06:50.500 - INFO - separator - No hardware acceleration could be configured, running in CPU mode 2024-11-10 04:06:50.500 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt... 2024-11-10 04:06:59.286 - INFO - mdxc_separator - MDXC Separator initialisation complete 2024-11-10 04:06:59.287 - INFO - separator - Load model duration: 00:00:08 2024-11-10 04:06:59.287 - INFO - separator - Starting separation process for audio_file_path: ./inputs/29951.wav
> 
> How can it still use PyTorch Version: 2.5.1+cpu when I removed it completely with "pip uninstall torch torchvision torchaudio" and installed "pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121" ?

You are installing torch and torchvision globally, that's why you can see it says `(base)`. You need to uninstall it and reinstall it from the env.

But don't worry, I just updated the installers to uninstall the CPU versions and install the new GPU versions from the Pytorch website.

So you can update UVR5-UI using the updater, but first delete the UVR5-UI env folder and then run the installer again.

Lmk if you find any problems, for now I'm skipping the torchaudio installation and changed the CUDA version to 12.1. This fix should work, but just maybe there could be more problems with torch or onnxruntime or cuda. ​​I don't have an NVIDIA GPU so I can't test it.

**Comment by CRCODE22** [comment]
> > I have installed torch-2.5.0+cu121 torchvision-0.20.0+cu121
> > Successfully installed torch-2.5.0+cu121 torchvision-0.20.0+cu121
> > (base) K:\UVR5-UI>pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121 Looking in indexes: https://download.pytorch.org/whl/test/cu121, https://pypi.ngc.nvidia.com Requirement already satisfied: torch==2.5.0 in e:\anaconda3\lib\site-packages (2.5.0+cu121) Requirement already satisfied: torchvision in e:\anaconda3\lib\site-packages (0.20.0+cu121) Requirement already satisfied: filelock in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.12.2) Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (4.12.2) Requirement already satisfied: networkx in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2.8.4) Requirement already satisfied: jinja2 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (3.1.2) Requirement already satisfied: fsspec in e:\anaconda3\lib\site-packages (from torch==2.5.0) (2023.6.0) Requirement already satisfied: sympy==1.13.1 in e:\anaconda3\lib\site-packages (from torch==2.5.0) (1.13.1) Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\anaconda3\lib\site-packages (from sympy==1.13.1->torch==2.5.0) (1.2.1) Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from torchvision) (1.23.5) Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in e:\anaconda3\lib\site-packages (from torchvision) (10.1.0) Requirement already satisfied: MarkupSafe>=2.0 in e:\anaconda3\lib\site-packages (from jinja2->torch==2.5.0) (2.1.1)
> > Still the software says the following:
> > 2024-11-10 04:06:50.474 - INFO - separator - Python Version: 3.10.12 2024-11-10 04:06:50.474 - INFO - separator - PyTorch Version: 2.5.1+cpu 2024-11-10 04:06:50.495 - INFO - separator - FFmpeg installed: ffmpeg version 2023-03-20-git-57afccc0ef-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers 2024-11-10 04:06:50.499 - INFO - separator - ONNX Runtime GPU package installed with version: 1.20.0 2024-11-10 04:06:50.500 - INFO - separator - No hardware acceleration could be configured, running in CPU mode 2024-11-10 04:06:50.500 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt... 2024-11-10 04:06:59.286 - INFO - mdxc_separator - MDXC Separator initialisation complete 2024-11-10 04:06:59.287 - INFO - separator - Load model duration: 00:00:08 2024-11-10 04:06:59.287 - INFO - separator - Starting separation process for audio_file_path: ./inputs/29951.wav
> > How can it still use PyTorch Version: 2.5.1+cpu when I removed it completely with "pip uninstall torch torchvision torchaudio" and installed "pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/cu121" ?
> 
> You are installing torch and torchvision globally, that's why you can see it says `(base)`. You need to uninstall it and reinstall it from the env.
> 
> But don't worry, I just updated the installers to uninstall the CPU versions and install the new GPU versions from the Pytorch website.
> 
> So you can update UVR5-UI using the updater, but first delete the UVR5-UI env folder and then run the installer again.
> 
> Lmk if you find any problems, for now I'm skipping the torchaudio installation and changed the CUDA version to 12.1. This fix should work, but just maybe there could be more problems with torch or onnxruntime or cuda. ​​I don't have an NVIDIA GPU so I can't test it.

Thank you for your replying and the updates I will see if they work and let you know. I did activate the environment before running the commands. I went to the env scripts folder and typed activate it then did a conda activate.

Base means the env was activated.

**Comment by CRCODE22** [comment]
I deleted the env and did as you suggested but the install script still installs the wrong version:

Requirement already satisfied: filelock in k:\uvr5-ui\env\lib\site-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in k:\uvr5-ui\env\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in k:\uvr5-ui\env\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in k:\uvr5-ui\env\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in k:\uvr5-ui\env\lib\site-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in k:\uvr5-ui\env\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in k:\uvr5-ui\env\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in k:\uvr5-ui\env\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in k:\uvr5-ui\env\lib\site-packages (from torchvision) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in k:\uvr5-ui\env\lib\site-packages (from jinja2->torch) (2.1.5)
Installing collected packages: torch, torchvision
Successfully installed torch-2.5.1+cu121 torchvision-0.20.1+cu121
Dependencies installation complete
