### ISSUE TITLE
why not gpu?i have a nvida

### ISSUE THREAD

**Issue by PeterRiver12** [Eddycrack864/UVR5-UI#17]
2024-11-23 15:24:20.441 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
~$ nvidia-smi
Sat Nov 23 15:27:11 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |

**Comment by Eddycrack864** [comment]
Please refer to this issue: https://github.com/Eddycrack864/UVR5-UI/issues/13

You probably downloaded the v1.5.1 release and installed it but did not update using the installer. That version doesn't have the patch to fix that problem yet, imma publish a new update
