### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by Dryesthalo98066** [Eddycrack864/UVR5-UI#26]
Hello, I'm having the same issue as that in issue#19 it looks like. I am installing on windows and I followed the guide. I have ffmpeg installed and set as path using the installation script. I then installed like normal using the script provided. I don't have python installed which could maybe be an issue? I don't have python installed for any of my other AI applications though so im not too sure.  Let me know if I can provide any more info. Thanks!

**Comment by Eddycrack864** [comment]
Interesting. Could you tell me the path where you are trying to install UVR5 UI? It seems that the dependencies were not installed, this is very weird. Because if you use my installation script it should install everything and when running it uses the python installed by my script, so it's not a problem that you don't have python, don't worry about that.

You could also run the file called status-checker.bat which is located in info/status-checker.bat, that will show you the status of audio-separator which is the core of UVR5 UI.

**Comment by Dryesthalo98066** [comment]
Yeah, This is the path that I am installing it at "C:\AIStuffCDrive\UVR5-UI(Better_UVR)\UVR5-UI". I get this when I run the audio checker "'.\\env\\Scripts\\audio-separator.exe' is not recognized as an internal or external command, operable program or batch file.".

**Comment by Eddycrack864** [comment]
Could you try installing it to C:\AIStuffCDrive\UVR5-UI?

**Comment by Eddycrack864** [comment]
After installation the folder should look like this:
![image](https://github.com/user-attachments/assets/61c42117-9038-471a-94f1-bffc658aa478)

Do you have the env folder? Inside it there should be many files, like these, along with the libraries in: C:\XXXXXX\env\Lib\site-packages, like this:
![image](https://github.com/user-attachments/assets/9fa8c4d5-7f3e-470c-b3ba-a0ab1fe57027)
Here u can see gradio, audio-separator, torch......

**Comment by Dryesthalo98066** [comment]
I'm trying this now, I have already gotten further in the installation this time. Ill let you know once its done. Thanks for the help so far!

**Comment by Eddycrack864** [comment]
You are welcome! I also want to find out why this problem occurs. I should probably make a precompiled version to avoid these problems.

**Comment by Dryesthalo98066** [comment]
It installed successfully it looks like! However when I try to run it I get this error.

 "Traceback (most recent call last):
  File "C:\AIStuffCDrive\UVR5-UI\app.py", line 638, in <module>
    with Translate("assets/languages/translation.yaml", placeholder_langs = ["en", "es", "it", "pt", "ms", "id", "ru", "uk", "th", "zh", "ja", "ko", "hi"]) as lang:
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\gradio_i18n\i18n.py", line 384, in Translate
    translation_dict = yaml.safe_load(f)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\AIStuffCDrive\UVR5-UI\env\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 4686: invalid continuation byte"

**Comment by Dryesthalo98066** [comment]
Yes that is correct.

**Comment by Eddycrack864** [comment]
If you still get UnicodeDecodeError errors after activating Beta: Use Unicode UTF-8 for worldwide language support. Use the UVR5 UI updater and try to open it again, for some reason the translations file gets corrupted sometimes when that error appears.

**Comment by Dryesthalo98066** [comment]
Got it, I will try this now. Thanks!

**Comment by Dryesthalo98066** [comment]
Looks like that fixed the issue! Thanks!

**Comment by Eddycrack864** [comment]
You are welcome!
