### ISSUE TITLE
Add pydantic==2.8.2 fastapi==0.112.0 starlette==0.37.2 dependencies

### ISSUE THREAD

**Issue by aris-py** [Eddycrack864/UVR5-UI#3]
gradio has a conficlt with pydantic
add this into requirements.txt
`pydantic==2.8.2
fastapi==0.112.0
starlette==0.37.2`

**Comment by Eddycrack864** [comment]
Thanks for the bug report for pydantic. The dependencies you provided fixed the bug and I also took the opportunity to update dependencies.

Thanks again.
